# Generated by Django 2.1.2 on 2018-12-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181208_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=256, verbose_name='标签'),
        ),
    ]
